repos:
-   hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
-   hooks:
    -   id: remove-tabs
    repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
