apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  artifacts:
  # image tags are relative; to specify an image repo (e.g. GCR), you
  # must provide a "default repo" using one of the methods described
  # here:
  # https://skaffold.dev/docs/concepts/#image-repository-handling
  - image: autoscaling-consumer
    context: consumer
    docker:
      cacheFrom:
        - golang:1.20-alpine
        - alpine:3.17
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true

manifests:
  kustomize:
    paths:
    - manifests

deploy:
  kubectl: {}
  kubeContext: minikube
  helm:
    releases:
      - name: crds
        chartPath: charts/crds
        upgradeOnChange: true
        wait: true

      - name: namespaces
        chartPath: charts/namespaces
        upgradeOnChange: true
        wait: true

      - name: prometheus
        repo: https://prometheus-community.github.io/helm-charts
        remoteChart: prometheus
        namespace: monitoring
        setValues:
          global:
            scrape_interval: 10s
          server:
            persistentVolume:
              enabled: false
          alertmanager:
            persistentVolume:
              enabled: false
          pushgateway:
            persistentVolume:
              enabled: false
        wait: false
        upgradeOnChange: true

      - name: prometheus-adapter
        repo: https://prometheus-community.github.io/helm-charts
        remoteChart: prometheus-adapter
        namespace: monitoring
        setValues:
          prometheus:
            url: http://prometheus-server.monitoring.svc.cluster.local
            port: 80
          logLevel: 10
          metricsRelistInterval: 30s
          rules:
            default: false
            external:
              - metricsQuery: max(nats_consumer_num_pending{<<.LabelMatchers>>}) by (consumer_name)
                name:
                  as: messages_pending
                  matches: ""
                resources:
                  namespaced: false
                seriesQuery: nats_consumer_num_pending{}
        wait: false
        upgradeOnChange: true

      - name: nats
        repo: https://nats-io.github.io/k8s/helm/charts/
        remoteChart: nats
        namespace: nats
        createNamespace: true
        setValues:
          nats:
            jetstream:
              enabled: true
          cluster:
            enabled: true
            replicas: 3
        version: 0.19.11
        wait: true

      - name: nack
        repo: https://nats-io.github.io/k8s/helm/charts
        remoteChart: nack
        namespace: nats
        createNamespace: true
        setValues:
          jetstream:
            nats:
              url: nats://nats:4222
          namespaced: true
        version: 0.21.0
        wait: false
