apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: app
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image:  autoscaling-consumer
        env:
          - name: NATS_URL
            value: nats://nats.nats.svc.cluster.local:4222
          - name: POLLING_TIMEOUT
            value: "1.0"
          - name: MESSAGES_PER_SECOND
            value: "1.0"
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
