apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer
  namespace: app
spec:
  pollingInterval: 3   # Optional. Default: 30 seconds
  cooldownPeriod: 10   # Optional. Default: 300 seconds
  minReplicaCount: 0   # Optional. Default: 0
  maxReplicaCount: 5   # Optional. Default: 100
  scaleTargetRef:
    kind: Deployment
    name: consumer
  triggers:
  - type: nats-jetstream
    metadata:
      natsServerMonitoringEndpoint: "nats.nats.svc.cluster.local:8222"
      account: "$G"
      stream: "EVENTS"
      consumer: "EVENTS_PROCESSING"
      lagThreshold: "10"
      activationLagThreshold: "30"
      useHttps: "false"