apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer
  namespace: app
spec:
  pollingInterval: 3   # Optional. Default: 30 seconds
  cooldownPeriod: 10   # Optional. Default: 300 seconds
  minReplicaCount: 1   # Optional. Default: 0
  maxReplicaCount: 10  # Optional. Default: 100
  scaleTargetRef:
    kind: Deployment
    name: consumer
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
      behavior:                                      # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 50
            periodSeconds: 30
          - type: Pods
            value: 4
            periodSeconds: 30
  triggers:
  - type: nats-jetstream
    metricType: AverageValue
    metadata:
      natsServerMonitoringEndpoint: "nats.nats.svc.cluster.local:8222"
      account: "$G"
      stream: "EVENTS"
      consumer: "EVENTS_PROCESSING"
      lagThreshold: "10"
      activationLagThreshold: "30"
      useHttps: "false"